# This is a sample build configuration for Python.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Dockerhub as your build environment.
image: python:3.6

pipelines:
  default:
    - step:
        script:
          - python --version
          - pip --version
          - pip install signac
          - pip install networkx
          - python setup.py build
          - python -m unittest discover tests/ -v
  branches:
    master:
      - step:
          image: themattrix/tox
          script:
            - python3.6 --version
            - pip3.6 --version
            - pip3.6 install -U coverage
            - pip3.6 install -U signac
            - pip3.6 install -U networkx
            - python3.6 -m coverage --version
            - tox --version
            - python3.6 setup.py build
            - python3.6 -m unittest discover tests/ -v
            - tox
            - python3.6 -m coverage report -i --include="flow*"
    develop:
      - step:
          image: themattrix/tox
          script:
            - python3.6 --version
            - pip3.6 --version
            - pip3.6 install -U coverage
            - pip3.6 install -U signac
            - pip3.6 install -U networkx
            - python3.6 -m coverage --version
            - tox --version
            - python3.6 setup.py build
            - python3.6 -m unittest discover tests/ -v
            - tox
            - python3.6 -m coverage report -i --include="flow*"
    v*:
      - step:
          image: themattrix/tox
          script:
            - python3.6 --version
            - pip3.6 --version
            - pip3.6 install -U coverage
            - pip3.6 install -U signac
            - pip3.6 install -U networkx
            - python3.6 -m coverage --version
            - tox --version
            - python3.6 setup.py build
            - python3.6 -m unittest discover tests/ -v
            - tox
            - python3.6 -m coverage report -i --include="flow*"
  tags:
   v*:
     - step:
          image: themattrix/tox
          script:
            - pip3.6 install -U twine
            - python3.6 --version
            - pip3.6 --version
            - pip3.6 install -U coverage
            - pip3.6 install -U signac
            - pip3.6 install -U networkx
            - python3.6 -m coverage --version
            - tox --version
            - twine --version
            - python3.6 setup.py build
            - python3.6 -m unittest discover tests/ -v
            - tox
            - python3.6 -m coverage report -i --include="flow*"
            - bash .deploy.bash
