# This is a sample build configuration for Python.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Dockerhub as your build environment.
image: continuumio/miniconda3

pipelines:
  default:
    - step:
        script:
          - conda --version
          - python --version
          - conda install flake8
          - python -m flake8 --show-source flow/
          - conda config --add channels glotzer
          - conda config --add channels conda-forge
          - conda create -n py27 --yes python=2.7 coverage signac enum34
          - source activate py27
          - python setup.py build
          - python -m coverage run -m unittest discover tests/
          - source deactivate
          - conda create -n py36 --yes python=3.6 coverage signac
          - source activate py36
          - python setup.py build
          - python -m coverage run -m unittest discover tests/
          - source deactivate
          - conda create -n py35 --yes python=3.5 coverage signac
          - source activate py35
          - python setup.py build
          - python -m coverage run -m unittest discover tests/
          - source deactivate
          - conda create -n py34 --yes python=3.4 coverage signac
          - source activate py34
          - python setup.py build
          - python -m coverage run -m unittest discover tests/
          - python -m coverage report
  branches:
    master:
      - step:
          script:
            - conda --version
            - python --version
            - conda install flake8
            - python -m flake8 --show-source flow/
            - conda config --add channels glotzer
            - conda config --add channels conda-forge
            - conda create -n py27 --yes python=2.7 coverage signac enum34
            - source activate py27
            - python setup.py build
            - python -m coverage run -m unittest discover tests/
            - source deactivate
            - conda create -n py36 --yes python=3.6 coverage signac
            - source activate py36
            - python setup.py build
            - python -m coverage run -m unittest discover tests/
            - source deactivate
            - conda create -n py35 --yes python=3.5 coverage signac
            - source activate py35
            - python setup.py build
            - python -m coverage run -m unittest discover tests/
            - source deactivate
            - conda create -n py34 --yes python=3.4 coverage signac hoomd jupyter matplotlib
            - source activate py34
            - python setup.py build
            - python -m coverage run -m unittest discover tests/
            - python -m coverage report
            - python setup.py install
            - git clone https://github.com/glotzerlab/signac-project-template.git template
            - cd template
            - python -m my_project.init 0
            - python -m my_project.status --detailed
            - python -m my_project.submit --test --ppn 1
            - python scripts/run.py auto
            - python -m my_project.status --detailed
            - python -m jupyter nbconvert --to html --execute analysis/notebook.ipynb
    develop:
      - step:
          script:
            - conda --version
            - python --version
            - conda install flake8
            - python -m flake8 --show-source flow/
            - conda config --add channels glotzer
            - conda config --add channels conda-forge
            - conda create -n py27 --yes python=2.7 coverage signac enum34
            - source activate py27
            - python setup.py build
            - python -m coverage run -m unittest discover tests/
            - source deactivate
            - conda create -n py36 --yes python=3.6 coverage signac
            - source activate py36
            - python setup.py build
            - python -m coverage run -m unittest discover tests/
            - source deactivate
            - conda create -n py35 --yes python=3.5 coverage signac
            - source activate py35
            - python setup.py build
            - python -m coverage run -m unittest discover tests/
            - source deactivate
            - conda create -n py34 --yes python=3.4 coverage signac hoomd jupyter matplotlib
            - source activate py34
            - python setup.py build
            - python -m coverage run -m unittest discover tests/
            - python -m coverage report
            - python setup.py install
            - git clone https://github.com/glotzerlab/signac-project-template.git template
            - cd template
            - python -m my_project.init 0
            - python -m my_project.status --detailed
            - python -m my_project.submit --test --ppn 1
            - python scripts/run.py auto
            - python -m my_project.status --detailed
            - python -m jupyter nbconvert --to html --execute analysis/notebook.ipynb
    release-*:
      - step:
          script:
            - conda --version
            - python --version
            - conda config --add channels glotzer
            - conda config --add channels conda-forge
            - conda create -n py27 --yes python=2.7 coverage signac enum34
            - source activate py27
            - python setup.py build
            - python -m coverage run -m unittest discover tests/
            - source deactivate
            - conda create -n py36 --yes python=3.6 coverage signac
            - source activate py36
            - python setup.py build
            - python -m coverage run -m unittest discover tests/
            - source deactivate
            - conda create -n py35 --yes python=3.5 coverage signac
            - source activate py35
            - python setup.py build
            - python -m coverage run -m unittest discover tests/
            - source deactivate
            - conda create -n py34 --yes python=3.4 coverage signac hoomd jupyter matplotlib
            - source activate py34
            - python setup.py build
            - python -m coverage run -m unittest discover tests/
            - python -m coverage report
            - python setup.py install
            - git clone https://github.com/glotzerlab/signac-project-template.git template
            - cd template
            - python -m my_project.init 0
            - python -m my_project.status --detailed
            - python -m my_project.submit --test --ppn 1
            - python scripts/run.py auto
            - python -m my_project.status --detailed
            - python -m jupyter nbconvert --to html --execute analysis/notebook.ipynb
  tags:
    release-*:
      - step:
          script:
            - conda --version
            - python --version
            - conda install flake8
            - python -m flake8 --show-source flow/
            - conda config --add channels glotzer
            - conda config --add channels conda-forge
            - conda create -n py27 --yes python=2.7 coverage signac enum34
            - source activate py27
            - python setup.py build
            - python -m coverage run -m unittest discover tests/
            - source deactivate
            - conda create -n py36 --yes python=3.6 coverage signac
            - source activate py36
            - python setup.py build
            - python -m coverage run -m unittest discover tests/
            - source deactivate
            - conda create -n py35 --yes python=3.5 coverage signac
            - source activate py35
            - python setup.py build
            - python -m coverage run -m unittest discover tests/
            - source deactivate
            - conda create -n py34 --yes python=3.4 coverage signac hoomd jupyter matplotlib
            - source activate py34
            - python setup.py build
            - python -m coverage run -m unittest discover tests/
            - python -m coverage report
            - python setup.py install
            - git clone https://github.com/glotzerlab/signac-project-template.git template
            - cd template
            - python -m my_project.init 0
            - python -m my_project.status --detailed
            - python -m my_project.submit --test --ppn 1
            - python scripts/run.py auto
            - python -m my_project.status --detailed
            - python -m jupyter nbconvert --to html --execute analysis/notebook.ipynb
            - cd ..
            - ./deploy.bash
